services:
  php:
    image: mvc-php
    build:
      context: ./
      dockerfile: config/Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/html/
      - ./config/local.conf:/etc/apache2/sites-available/000-default.conf
  node:
    image: node:18.14.2-alpine3.17
    user: "node"
    working_dir: /home/node/app
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: 
      - ./:/home/node/app
    command: "yarn watch"
  
  db:
    image: mysql:8.0.32-debian
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: mvc
      MYSQL_PASSWORD: mvc
      MYSQL_DATABASE: mvc
    ports:
      - "3311:3306"
    volumes:
      - ./var/db:/var/lib/mysql
